language: python
dist: xenial
sudo: required
cache:
- apt
addons: 
apt: 
packages:
- curl
install:
- sudo curl -sL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
- sudo unzip -d /usr/local/bin /tmp/terraform.zip
script:
- terraform fmt
- terraform init
- terraform apply
- terraform destroy
before_install:
- openssl aes-256-cbc -K $encrypted_cbf0f2d9b541_key -iv $encrypted_cbf0f2d9b541_iv
  -in key.enc -out key -d
- tar -xvf key
